-- ============================================================================
-- Supabase Schema for PromptShot 🎯
-- Run this in your Supabase SQL Editor to initialize the database tables,
-- RLS policies, and triggers.
-- ============================================================================

-- 1. Challenges Table
CREATE TABLE IF NOT EXISTS public.challenges (
  id TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  difficulty TEXT NOT NULL,
  target_output TEXT NOT NULL,
  ideal_prompt TEXT NOT NULL,
  char_count INTEGER NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  ideal_water_ml NUMERIC,
  ideal_co2_grams NUMERIC
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.challenges ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Challenges
CREATE POLICY "Allow public read access to challenges"
  ON public.challenges FOR SELECT
  USING (true);


-- 2. Profiles Table (User Streak and Stats)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  streak INTEGER NOT NULL DEFAULT 0,
  last_played DATE
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Profiles
CREATE POLICY "Allow public read access to profiles"
  ON public.profiles FOR SELECT
  USING (true);

CREATE POLICY "Allow users to update their own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Allow users to insert their own profile"
  ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

-- Trigger to automatically create a profile on user sign-up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, streak)
  VALUES (new.id, 0)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 3. Scores Table (User attempts / Leaderboard entries)
CREATE TABLE IF NOT EXISTS public.scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  challenge_id TEXT REFERENCES public.challenges(id) ON DELETE CASCADE NOT NULL,
  accuracy INTEGER NOT NULL,
  format INTEGER NOT NULL,
  brevity INTEGER NOT NULL,
  total INTEGER NOT NULL,
  user_prompt TEXT NOT NULL,
  played_at DATE NOT NULL DEFAULT CURRENT_DATE,
  water_ml NUMERIC NOT NULL,
  co2_grams NUMERIC NOT NULL
);

-- Enable RLS
ALTER TABLE public.scores ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Scores
CREATE POLICY "Allow public read access to scores"
  ON public.scores FOR SELECT
  USING (true);

CREATE POLICY "Allow authenticated users to insert their own scores"
  ON public.scores FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow authenticated users to delete their own scores"
  ON public.scores FOR DELETE
  USING (auth.uid() = user_id);


-- ============================================================================
-- Seed Initial Challenges
-- ============================================================================
INSERT INTO public.challenges (id, category, difficulty, target_output, ideal_prompt, char_count, active, ideal_water_ml, ideal_co2_grams) VALUES
('b001', 'PARAGRAPH', 'BEGINNER', 'Black holes are regions of space where gravity is so strong that nothing, not even light, can escape. The boundary surrounding a black hole is called the event horizon. Once anything crosses this line, it cannot return.', 'Explain what a black hole and its event horizon are in three sentences. Mention that gravity prevents light from escaping.', 251, true, 11, 0.111),
('b002', 'TONE', 'BEGINNER', 'Hey Priya, I''m so sorry but I have to bail tonight 😞 I''ve had the worst headache all day and I know I''d be terrible company. Can we reschedule for next weekend? I''ll make it up to you!', 'Text to Priya canceling tonight, headache, apologize, suggest rescheduling next weekend.', 184, true, 10, 0.105),
('b003', 'ROLE', 'BEGINNER', 'Imagine a clock on a super fast spaceship. To us watching from Earth, that clock ticks slower than ours. This happens because time bends when you travel close to the speed of light. It is called time dilation.', 'Explain time dilation on a fast spaceship to a kid. Mention clocks ticking slower and speed of light in 3 sentences.', 226, true, 11, 0.109),
('b004', 'LIST', 'BEGINNER', 'Edrik Stormweaver, Edrik Valerius, Edrik Blackwood, Edrik Thorn, Edrik Ironwood, Edrik Shadowend, Edrik Dawnrunner, Edrik Frostfield, Edrik Kingslayer, Edrik Wyrmbreaker.', 'List exactly 10 fantasy last names starting with capital letters, paired with first name Edrik, separated by commas.', 180, true, 11, 0.106),
('b005', 'TONE', 'BEGINNER', 'Hey roommates, could we please make sure to wash all pots and pans tonight? The sink is completely full and it''s getting hard to prep breakfast in the morning. Thanks for understanding!', 'Roommate text politely asking to wash pots and pans tonight because sink is full and morning breakfast prep is hard.', 211, true, 11, 0.107),
('b006', 'PARAGRAPH', 'BEGINNER', 'It would still take 30 minutes. All 10 shirts can dry at the same time on the clothesline. Putting more shirts out to dry does not increase the drying time for each individual shirt.', 'Answer the riddle: if it takes 30 mins to dry 5 shirts, how long to dry 10? Explain that they dry at the same time.', 198, true, 11, 0.107),
('b007', 'TONE', 'BEGINNER', 'Baking soda is a natural, non-toxic cleaner. It absorbs tough odors, scrubs away kitchen stains without scratching surfaces, and balances pH levels, making it safe for kids and pets.', 'Rewrite dry technical baking soda details into a warm, feature-focused blurb highlighting safety for kids and pets.', 190, true, 11, 0.107),
('p001', 'CONSTRAINTS', 'PRO', 'CUDA is Nvidia''s proprietary platform, offering deep integration and maximum performance on Nvidia hardware. OpenCL is an open, cross-platform standard supporting AMD, Intel, and Nvidia chips, but with less optimization. Choose CUDA for Nvidia GPUs, and OpenCL for heterogeneous hardware.', 'Compare CUDA and OpenCL programming models. Highlight hardware compatibility and performance, and provide a recommendation. Under 50 words.', 298, true, 12, 0.118),
('p002', 'LIST', 'PRO', 'Here are 3 ways to monetize a high-end PC:\n1. 3D Rendering & Video Editing: Rent your GPU power on decentralized networks.\n2. Game Server Hosting: Host multiplayer game servers for a small monthly fee.\n3. AI Model Tuning: Run local low-rank adaptation training runs for clients.', 'List 3 creative, legal ways a student can earn income using a gaming PC. Use numbered list with bold titles and short descriptions.', 292, true, 12, 0.116),
('p003', 'CODE', 'PRO', '```bash\n#!/bin/bash\n# Continually ping Google DNS and log failures\nwhile true; do\n  if ! ping -c 1 8.8.8.8 >/dev/null 2>&1; then\n    echo "[$(date)] Ping failed!" >> ping_errors.log\n  fi\n  sleep 5\ndone\n```', 'Write a bash script containing a while loop that pings 8.8.8.8. If it fails, log timestamped failure message to ping_errors.log. Sleep 5s.', 227, true, 11, 0.111),
('p004', 'ROLE', 'PRO', 'Public key cryptography is like a mailbox. Anyone can put a letter in through the slot using the public key, which is open to everyone. But only the owner of the mailbox can open it and read the letters using the private key, which is kept secret. This keeps messages safe.', 'Explain public key cryptography using a mailbox lock-and-key analogy. Cover how public and private keys operate to secure messages.', 294, true, 12, 0.116),
('p005', 'CODE', 'PRO', '```css\n.card {\n  background: rgba(255, 255, 255, 0.1);\n  backdrop-filter: blur(10px);\n  border: 1px solid rgba(255, 255, 255, 0.2);\n  border-radius: 16px;\n  box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.3);\n  padding: 24px;\n  color: #fff;\n}\n```', 'Write a clean CSS .card block with glassmorphism (translucent background, blur), white border, rounded corners, drop shadow, and padding.', 232, true, 11, 0.114),
('p006', 'TONE', 'PRO', 'Hey everyone 👋 For the Airbnb deposit we each owe $47.50 — can everyone Venmo Zara by Wednesday? We need to confirm the booking by Thursday night so please don''t leave her hanging. Let me know ASAP if you can''t make it work!', 'Group chat: 4 people Venmo Zara $47.50 for Airbnb deposit by Wednesday, booking deadline Thursday night, casual but urgent.', 236, true, 11, 0.111),
('p007', 'ROLE', 'PRO', 'Hi Professor Okafor, I''m a sophomore in Intro to Economics. I found your recent talk on decision fatigue fascinating. Do you have any openings for undergraduate research assistants next semester? I would love to learn more and discuss how I could contribute to your project.', 'Polite cold email to Professor Okafor: sophomore, loved his decision fatigue talk, ask about undergraduate research assistant openings next semester.', 297, true, 12, 0.117),
('e001', 'CONSTRAINTS', 'EXPERT', 'If you love the mind-bending time travel of Dark, check out: 1. Alan Wake 2 (cosmic horror, shifting realities), 2. Outer Wilds (time loop exploration, stellar mystery), and 3. BioShock Infinite (parallel dimensions, rich narrative). All match the dark, mysterious atmosphere you want.', 'Recommend 3 video games (with short parenthetical descriptions) for a fan of the TV show Dark, focusing on mystery, time-travel, and dark atmosphere. Under 60 words.', 298, true, 12, 0.119),
('e002', 'ROLE', 'EXPERT', 'Midnights in the kitchen, sweating in my jeans / Underpants are soggy, if you know what I mean / Running through the heatwave, crying in the park / These damp cotton fabrics leaving their wet mark / Oh, it''s a cruel summer, but my drawers are cold and wet.', 'Write Swift-style song lyrics about soggy/sweaty underpants during a hot summer. Incorporate dramatic Midnights/Cruel Summer themes. Under 55 words.', 298, true, 12, 0.116),
('e003', 'CONSTRAINTS', 'EXPERT', 'L2 regularization prevents overfitting by adding a penalty proportional to the square of weight magnitudes to the loss function. This discourages weights from growing excessively large, smoothing the model''s decision boundaries and ensuring it doesn''t overfit to training noise.', 'Explain how L2 regularization prevents machine learning overfitting. Focus on the penalty term, weight magnitudes, and decision boundary smoothing. Keep it precise and technical.', 296, true, 12, 0.12),
('e004', 'CODE', 'EXPERT', '```python\ndef get_primes(numbers):\n    # Filter and return list of prime numbers\n    def is_prime(n):\n        if n < 2: return False\n        for i in range(2, int(n**0.5) + 1):\n            if n % i == 0: return False\n        return True\n    return [num for num in numbers if is_prime(num)]\n```', 'Write a Python function get_primes(numbers) that filters a list for primes. Include a helper function is_prime, use square root limit for efficiency, and add a single comment.', 301, true, 12, 0.121),
('e005', 'TONE', 'EXPERT', 'Dear Landlord, I am writing to report that the bathroom sink has been leaking since last week. Water is starting to pool and damage the cabinet beneath. Please send maintenance to fix this as soon as possible to prevent further water damage. Thank you for your prompt attention.', 'Polite but urgent maintenance request to landlord: bathroom sink leaking since last week, water pooling and cabinet damage, ask for quick fix to prevent further damage.', 292, true, 12, 0.119),
('e006', 'PARAGRAPH', 'EXPERT', 'The soup is ice. Even though the refrigeration truck is at 0 degrees, the soup starts warm or liquid, and over time in a sealed box with ice, the system reaches thermal equilibrium. Since 0°C is the freezing point of water, the soup will eventually freeze solid, and the ice remains.', 'Solve this riddle: a warm bowl of soup and ice cube are put in a box in a 0°C truck. What happens to the soup and ice? Explain thermal equilibrium and freezing point.', 299, true, 12, 0.12),
('e007', 'CONSTRAINTS', 'EXPERT', 'The Rosetta Stone, discovered in 1799 by French soldiers in Egypt, is a granodiorite stele inscribed with three scripts: Hieroglyphic, Demotic, and Ancient Greek. This trilingual decree allowed scholars like Champollion to decode Egyptian hieroglyphs by comparing them to the Greek text.', 'Explain how the Rosetta Stone was discovered and used to decode hieroglyphs. Mention the three scripts, the year of discovery, and Champollion''s contribution. Under 55 words.', 296, true, 12, 0.121)
ON CONFLICT (id) DO NOTHING;

