-- ============================================================================
-- Supabase Schema for PromptShot 🎯
-- Run this in your Supabase SQL Editor to initialize the database tables,
-- RLS policies, and triggers.
-- ============================================================================

-- 1. Challenges Table
CREATE TABLE IF NOT EXISTS public.challenges (
  id TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  difficulty TEXT NOT NULL,
  target_output TEXT NOT NULL,
  ideal_prompt TEXT NOT NULL,
  char_count INTEGER NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.challenges ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Challenges
CREATE POLICY "Allow public read access to challenges"
  ON public.challenges FOR SELECT
  USING (true);


-- 2. Profiles Table (User Streak and Stats)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  streak INTEGER NOT NULL DEFAULT 0,
  last_played DATE
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Profiles
CREATE POLICY "Allow public read access to profiles"
  ON public.profiles FOR SELECT
  USING (true);

CREATE POLICY "Allow users to update their own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Allow users to insert their own profile"
  ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

-- Trigger to automatically create a profile on user sign-up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, streak)
  VALUES (new.id, 0)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 3. Scores Table (User attempts / Leaderboard entries)
CREATE TABLE IF NOT EXISTS public.scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  challenge_id TEXT REFERENCES public.challenges(id) ON DELETE CASCADE NOT NULL,
  accuracy INTEGER NOT NULL,
  format INTEGER NOT NULL,
  brevity INTEGER NOT NULL,
  total INTEGER NOT NULL,
  user_prompt TEXT NOT NULL,
  played_at DATE NOT NULL DEFAULT CURRENT_DATE,
  water_ml NUMERIC NOT NULL,
  co2_grams NUMERIC NOT NULL
);

-- Enable RLS
ALTER TABLE public.scores ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Scores
CREATE POLICY "Allow public read access to scores"
  ON public.scores FOR SELECT
  USING (true);

CREATE POLICY "Allow authenticated users to insert their own scores"
  ON public.scores FOR INSERT
  WITH CHECK (auth.uid() = user_id);


-- ============================================================================
-- Seed Initial Challenges
-- ============================================================================
INSERT INTO public.challenges (id, category, difficulty, target_output, ideal_prompt, char_count, active) VALUES
('001', 'PARAGRAPH', 'BEGINNER', 'The water cycle, also known as the hydrological cycle, describes the continuous movement of water through Earth''s systems. Water evaporates from oceans and lakes, rises as vapor, condenses into clouds, and falls as precipitation. This process distributes fresh water across the planet and regulates global temperature.', 'Explain the water cycle in 3 sentences. Include: evaporation, condensation, and precipitation. Keep it factual and concise.', 312, true),
('002', 'CODE', 'PRO', 'function debounce(fn, delay) {
  let timer;
  return function(...args) {
    clearTimeout(timer);
    timer = setTimeout(() => fn.apply(this, args), delay);
  };
}', 'Write a JavaScript debounce function. It should accept a function and delay in ms, return a new function that clears and resets a timer on each call, and execute the original function after the delay.', 148, true),
('003', 'LIST', 'EXPERT', 'Principles of effective feedback:
• Specific over general — cite the exact behavior
• Timely — given close to the event
• Actionable — the receiver can do something with it
• Separates behavior from identity — ''this report was unclear'' not ''you are unclear''
• Two-way — invites response', 'List the principles of effective feedback as bullet points. Each should be a short label followed by a one-sentence explanation. Include: specificity, timing, actionability, behavior vs identity, and dialogue.', 328, true),
('004', 'ROLE', 'PRO', 'As your interview coach, focus on three things: tighten the opening story, quantify the project impact, and prepare one recovery answer for mistakes. Practice aloud twice, then trim anything that sounds memorized.', 'Act as an interview coach. Give concise advice for improving a software engineer''s behavioral interview answer. Include exactly 3 focus areas plus one practice instruction. Sound direct and supportive.', 214, true),
('005', 'TONE', 'BEGINNER', 'Thanks for sending this over. I can review it by Friday afternoon. If you need a faster turnaround, please send the two sections you want prioritized and I will look at those first.', 'Write a polite but firm reply to a coworker asking for a document review. Say you can review it by Friday afternoon. If they need it sooner, ask them to send the two priority sections first.', 181, true),
('006', 'CONSTRAINTS', 'EXPERT', 'Urban balcony garden checklist:
• 6+ hours of light
• Containers with drainage
• Lightweight potting mix
• Herbs or compact greens
• Watering plan for hot days
Avoid: invasive plants, heavy soil, and pesticide sprays.', 'Create a balcony garden checklist for a city apartment. Use bullet points. Include light, containers, soil, plant choices, and watering. Add an Avoid line with invasive plants, heavy soil, and pesticide sprays.', 222, true),
('007', 'PARAGRAPH', 'PRO', 'A transformer is an AI architecture that reads words in relation to one another instead of one at a time. That lets it notice which words matter most in a sentence, even when they are far apart. This is why modern chatbots can follow context across longer questions.', 'Explain what a transformer is in 3 sentences for a curious high school student. Avoid equations. Emphasize attention, relationships between words, and why it helps chatbots follow context.', 274, true)
ON CONFLICT (id) DO NOTHING;
