-- ============================================================================
-- Supabase Schema for PromptShot 🎯
-- Run this in your Supabase SQL Editor to initialize the database tables,
-- RLS policies, and triggers.
-- ============================================================================

-- 1. Challenges Table
CREATE TABLE IF NOT EXISTS public.challenges (
  id TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  difficulty TEXT NOT NULL,
  target_output TEXT NOT NULL,
  ideal_prompt TEXT NOT NULL,
  char_count INTEGER NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.challenges ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Challenges
CREATE POLICY "Allow public read access to challenges"
  ON public.challenges FOR SELECT
  USING (true);


-- 2. Profiles Table (User Streak and Stats)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  streak INTEGER NOT NULL DEFAULT 0,
  last_played DATE
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Profiles
CREATE POLICY "Allow public read access to profiles"
  ON public.profiles FOR SELECT
  USING (true);

CREATE POLICY "Allow users to update their own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Allow users to insert their own profile"
  ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

-- Trigger to automatically create a profile on user sign-up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, streak)
  VALUES (new.id, 0)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 3. Scores Table (User attempts / Leaderboard entries)
CREATE TABLE IF NOT EXISTS public.scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  challenge_id TEXT REFERENCES public.challenges(id) ON DELETE CASCADE NOT NULL,
  accuracy INTEGER NOT NULL,
  format INTEGER NOT NULL,
  brevity INTEGER NOT NULL,
  total INTEGER NOT NULL,
  user_prompt TEXT NOT NULL,
  played_at DATE NOT NULL DEFAULT CURRENT_DATE,
  water_ml NUMERIC NOT NULL,
  co2_grams NUMERIC NOT NULL
);

-- Enable RLS
ALTER TABLE public.scores ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Scores
CREATE POLICY "Allow public read access to scores"
  ON public.scores FOR SELECT
  USING (true);

CREATE POLICY "Allow authenticated users to insert their own scores"
  ON public.scores FOR INSERT
  WITH CHECK (auth.uid() = user_id);


-- ============================================================================
-- Seed Initial Challenges
-- ============================================================================
INSERT INTO public.challenges (id, category, difficulty, target_output, ideal_prompt, char_count, active) VALUES
('001', 'TONE', 'BEGINNER', 'Hi Dave, thanks for the invite. Since my calendar is fully booked this week, could you send over the key questions or agenda via Slack/email? I''ll review them and reply asynchronously by end of day today so we can save time.', 'Write a polite but direct response to a coworker named Dave, declining a sync invite because your calendar is booked. Ask him to send the agenda/questions via Slack/email instead, and promise an async reply by end of day. Keep it under 45 words.', 218, true),
('002', 'CODE', 'PRO', 'Hey team, my local branch is out of sync after an interactive rebase mismatch. I am force-pushing the origin branch from yesterday to reset it. No other branches are affected, and I will have the clean PR ready in 30 minutes.', 'Write a brief Slack update to your dev team. Explain that your branch is out of sync due to a rebase mismatch, you are force-pushing yesterday''s origin branch to reset it, and no other branches are affected. State the PR will be ready in 30 minutes. Keep it professional and direct.', 224, true),
('003', 'CONSTRAINTS', 'EXPERT', 'Translation: I was laid off along with 15% of the staff. The corporate pivot failed, the culture was toxic, and my equity is worth zero. I am now unemployed and looking for a job that pays actual money.', 'Translate a hype-filled corporate announcement into a raw, brutally honest summary: mention being laid off in a 15% cut, the failed corporate pivot, toxic culture, worthless equity, and looking for a new role. Prefix with ''Translation: ''.', 204, true),
('004', 'ROLE', 'PRO', 'Listen up, champ! Those failing unit tests are just mental blocks. We don''t skip debug day. Put your developer belt on, stack those print statements, and push that refactored commit. No excuses, let''s get those green checkmarks!', 'Act as a passionate, hyperactive gym bro personal trainer. Write a short motivational paragraph urging a software developer to fix their failing unit tests. Use phrases like ''debug day'', ''green checkmarks'', and ''no excuses''.', 226, true),
('005', 'LIST', 'BEGINNER', 'Survival Checklist:
1. Mute button checked twice (safety first)
2. Camera on ''thoughtful nod'' loop
3. Coffee mug filled to the brim
4. Dual-monitor setup hides actual work
5. Pre-drafted Slack update ready for the end', 'Create a 5-item survival checklist for surviving a long, boring Zoom meeting. Use bullet numbers. Focus on mute checks, camera nods, coffee, hiding work, and pre-drafted status updates. Start with the title ''Survival Checklist:''.', 216, true),
('006', 'TONE', 'EXPERT', 'Dear Landlord, this is a formal notice regarding active water damage in the living room ceiling. Per state tenancy guidelines, this requires urgent mitigation to prevent structural mold. Please confirm when the repair team will arrive today.', 'Write a formal email notice to your landlord about active ceiling water damage. Reference state tenancy guidelines, request urgent mitigation to prevent mold, and ask for repair confirmation today. Sound firm, legal, and professional.', 243, true),
('007', 'TONE', 'PRO', 'Hi team, I am following up on invoice #1042 which is now 60 days overdue. Please reply with the payment confirmation status by Friday. A late fee of 5% will be applied starting next week per our contract terms.', 'Write a professional follow-up email to a client for invoice #1042 that is 60 days overdue. Request a payment confirmation status by Friday. Mention a 5% late fee starting next week based on contract terms. Keep it direct and firm.', 212, true)
ON CONFLICT (id) DO NOTHING;
